In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import keras
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout
from keras.optimizers import SGD

Using TensorFlow backend.


In [2]:
#Lectura de datos 
data = pd.read_csv('DEPURACION_FINAL.csv', sep=',')
data

AÑO  MES     DIA  FECHA  HORA  KW-H
0      2015    1  jueves      1     0  3200
1      2015    1  jueves      1     1  3200
2      2015    1  jueves      1     2  2400
3      2015    1  jueves      1     3  2400
4      2015    1  jueves      1     4  2400
...     ...  ...     ...    ...   ...   ...
43819  2019   12  martes     31    19  3400
43820  2019   12  martes     31    20  3600
43821  2019   12  martes     31    21  3800
43822  2019   12  martes     31    22  4000
43823  2019   12  martes     31    23  4000

[43824 rows x 6 columns]

In [3]:
#Verificacion de nans 
data.isnull().values.any()
data.isnull().sum().sum()

data.isnull().sum()

AÑO      0
MES      0
DIA      0
FECHA    0
HORA     0
KW-H     0
dtype: int64

In [4]:
#Variable categrica DIA a numérica
data['DIA'] = data['DIA'].map({'lunes': 1 ,
                                           'martes': 2,
                                           'miercoles': 3,
                                           'miércoles': 3,
                                           'jueves': 4 , 
                                           'viernes': 5, 
                                           'sábado': 6,
                                           'sabado': 6,  #inconsistencia en la data por las tildes
                                           'domingo': 7})




AÑO  MES  DIA  FECHA  HORA  KW-H
0   2015    1    4      1     0  3200
1   2015    1    4      1     1  3200
2   2015    1    4      1     2  2400
3   2015    1    4      1     3  2400
4   2015    1    4      1     4  2400
5   2015    1    4      1     5  2400
6   2015    1    4      1     6  2400
7   2015    1    4      1     7  2400
8   2015    1    4      1     8  2400
9   2015    1    4      1     9  2600
10  2015    1    4      1    10  2600
11  2015    1    4      1    11  2600
12  2015    1    4      1    12  2600
13  2015    1    4      1    13  2600
14  2015    1    4      1    14  2600
15  2015    1    4      1    15  2600
16  2015    1    4      1    16  2600
17  2015    1    4      1    17  2300
18  2015    1    4      1    18  2300
19  2015    1    4      1    19  2300
20  2015    1    4      1    20  2300
21  2015    1    4      1    21  2400
22  2015    1    4      1    22  2400
23  2015    1    4      1    23  2400
24  2015    1    5      2     0  2400
25  2015    1    5      2     1  2400
26  2015    1    5      2     2  2400
27  2015    1    5      2     3  2400
28  2015    1    5      2     4  2200
29  2015    1    5      2     5  2200
30  2015    1    5      2     6  2200
31  2015    1    5      2     7  2200
32  2015    1    5      2     8  2200
33  2015    1    5      2     9  2200
34  2015    1    5      2    10  2200
35  2015    1    5      2    11  2200
36  2015    1    5      2    12  2200
37  2015    1    5      2    13  3100
38  2015    1    5      2    14  3400
39  2015    1    5      2    15  3400
40  2015    1    5      2    16  3400
41  2015    1    5      2    17  3300
42  2015    1    5      2    18  3700
43  2015    1    5      2    19  3700
44  2015    1    5      2    20  3700
45  2015    1    5      2    21  3700
46  2015    1    5      2    22  2900
47  2015    1    5      2    23  2700
48  2015    1    6      3     0  2500
49  2015    1    6      3     1  2500

In [6]:
data.tail(50)

AÑO  MES  DIA  FECHA  HORA    KW-H
43774  2019   12    7     29    22  3200.0
43775  2019   12    7     29    23  2800.0
43776  2019   12    1     30     0  2400.0
43777  2019   12    1     30     1  2400.0
43778  2019   12    1     30     2  2000.0
43779  2019   12    1     30     3  2000.0
43780  2019   12    1     30     4  2000.0
43781  2019   12    1     30     5  2000.0
43782  2019   12    1     30     6  2000.0
43783  2019   12    1     30     7  1800.0
43784  2019   12    1     30     8  1800.0
43785  2019   12    1     30     9  1800.0
43786  2019   12    1     30    10  1900.0
43787  2019   12    1     30    11  1900.0
43788  2019   12    1     30    12  1900.0
43789  2019   12    1     30    13  1900.0
43790  2019   12    1     30    14  2000.0
43791  2019   12    1     30    15  2100.0
43792  2019   12    1     30    16  2200.0
43793  2019   12    1     30    17  2100.0
43794  2019   12    1     30    18  2000.0
43795  2019   12    1     30    19  2500.0
43796  2019   12    1     30    20  2500.0
43797  2019   12    1     30    21  2500.0
43798  2019   12    1     30    22  2500.0
43799  2019   12    1     30    23  2400.0
43800  2019   12    2     31     0  2400.0
43801  2019   12    2     31     1  2400.0
43802  2019   12    2     31     2  2600.0
43803  2019   12    2     31     3  2600.0
43804  2019   12    2     31     4  2800.0
43805  2019   12    2     31     5  2700.0
43806  2019   12    2     31     6  2600.0
43807  2019   12    2     31     7  3000.0
43808  2019   12    2     31     8  3100.0
43809  2019   12    2     31     9  3600.0
43810  2019   12    2     31    10  4000.0
43811  2019   12    2     31    11  4100.0
43812  2019   12    2     31    12  4100.0
43813  2019   12    2     31    13  4100.0
43814  2019   12    2     31    14  3900.0
43815  2019   12    2     31    15  3900.0
43816  2019   12    2     31    16  3600.0
43817  2019   12    2     31    17  3400.0
43818  2019   12    2     31    18  3400.0
43819  2019   12    2     31    19  3400.0
43820  2019   12    2     31    20  3600.0
43821  2019   12    2     31    21  3800.0
43822  2019   12    2     31    22  4000.0
43823  2019   12    2     31    23  4000.0

In [5]:
#Transformacion de datos a numerica

data['KW-H'] = [valor.replace(",", ".") for valor in data['KW-H'] ]
data['KW-H'] = [float(valor) for valor in data['KW-H'] ]



AÑO      2018.0
MES         1.0
DIA         1.0
FECHA       1.0
HORA        2.0
KW-H        4.1
Name: 26306, dtype: float64

In [87]:
#Dividir los datos de entrenamiento y de test
# No se puede utilizar train test split, debemos dividir en el ultimo segmento 
# x = data.iloc[:,:-1]
# y = data.iloc[:,-1]

# x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 30)

#Tomamos los datos para validacion todo lo del 2019


data_test = data[data['AÑO'] == 2019]
data_train = data[data['AÑO'] != 2019]
data_train


AÑO  MES  DIA  FECHA  HORA    KW-H
0      2015    1    4      1     0  3200.0
1      2015    1    4      1     1  3200.0
2      2015    1    4      1     2  2400.0
3      2015    1    4      1     3  2400.0
4      2015    1    4      1     4  2400.0
...     ...  ...  ...    ...   ...     ...
35059  2018   12    1     31    19  2300.0
35060  2018   12    1     31    20  2200.0
35061  2018   12    1     31    21  2800.0
35062  2018   12    1     31    22  2800.0
35063  2018   12    1     31    23  2900.0

[35064 rows x 6 columns]

In [89]:
#Normalizacion de los datos
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range = (0,1))
data_train_scaled = sc.fit_transform(data_train)
print(data_train_scaled.shape)
data_train_scaled


(35064, 6)


array([[0.        , 0.        , 0.5       , 0.        , 0.        ,
        0.66666667],
       [0.        , 0.        , 0.5       , 0.        , 0.04347826,
        0.66666667],
       [0.        , 0.        , 0.5       , 0.        , 0.08695652,
        0.5       ],
       ...,
       [1.        , 1.        , 0.        , 1.        , 0.91304348,
        0.58333333],
       [1.        , 1.        , 0.        , 1.        , 0.95652174,
        0.58333333],
       [1.        , 1.        , 0.        , 1.        , 1.        ,
        0.60416667]])

In [57]:
#Tenemos que entrenar la red por bloques de datos 
#Time_step es el tamaño del bloque 
#Cada n datos genera una salida 
#Tomamos bloques de 60 bloques consecutivos 
time_step = 60 
X_train = [] #Lista de conjuntos de 60 datos 
Y_train = []
m = len(data_train_scaled)
for i in range(time_step, m):
    X_train.append(data_train_scaled[i-time_step:i,0]) #Guardamos 60 valores
    Y_train.append(data_train_scaled[i, 0]) #Guardamos el ultimo valor (60) 
X_train, Y_train = np.array(X_train), np.array(Y_train) #Usamos np por reshape y optimizacion



In [58]:
X_train.shape, Y_train.shape

((35004, 60), (35004,))

In [32]:
# def create_sequence(dataset):
#   sequences = []
#   labels = []

#   start_idx = 0

#   for stop_idx in range(50,len(dataset)): # Selecting 50 rows at a time
#     sequences.append(dataset.iloc[start_idx:stop_idx])
#     labels.append(dataset.iloc[stop_idx])
#     start_idx += 1
#   return (np.array(sequences),np.array(labels))

array([[0.        , 0.        , 0.83333333, 0.06666667, 0.08695652],
       [0.        , 0.        , 0.83333333, 0.06666667, 0.13043478],
       [0.        , 0.        , 0.83333333, 0.06666667, 0.17391304],
       ...,
       [1.        , 1.        , 0.        , 1.        , 0.91304348],
       [1.        , 1.        , 0.        , 1.        , 0.95652174],
       [1.        , 1.        , 0.        , 1.        , 1.        ]])

In [56]:


# X_train, Y_train = create_sequence(pd.DataFrame(data_array_train))

# X_train.shape, Y_train.shape
# Y_train

((35014, 50, 6), (35014, 6))

In [60]:
#Obligatorio el reshape de los datos, es obligatorio por Keras
#Llevamos de dos a 3 dimensiones nuestro arreglo 
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1)) #Agregamos una nueva dimension
X_train.shape, Y_train.shape

((35004, 60, 1), (35004,))

In [62]:
#Parametros para el LSTM
from keras.layers import LSTM
from sklearn.metrics import mean_squared_error
dim_entrada = (X_train.shape[1],X_train.shape[2])
dim_salida = 1 
num_neuronas = 50
dim_entrada

(60, 1)

In [64]:
model = Sequential()
#Capa 1 
model.add(LSTM(units=num_neuronas, return_sequences = True, input_shape=dim_entrada))
#TODO posible dropout
#Capa 2
model.add(LSTM(units=num_neuronas))

#capa de salida 
model.add(Dense(units = dim_salida))
model.compile(optimizer='rmsprop', loss='mse') #mean_squared_error

#Entrenamiento 
model.fit(X_train, Y_train, epochs = 20, batch_size = 128)

Epoch 1/20
35004/35004 [==============================] - 122s 3ms/step - loss: 0.0046
Epoch 2/20
35004/35004 [==============================] - 124s 4ms/step - loss: 0.0013
Epoch 3/20
35004/35004 [==============================] - 138s 4ms/step - loss: 8.9367e-04
Epoch 4/20
35004/35004 [==============================] - 141s 4ms/step - loss: 6.9120e-04
Epoch 5/20
35004/35004 [==============================] - 146s 4ms/step - loss: 5.7957e-04
Epoch 6/20
35004/35004 [==============================] - 140s 4ms/step - loss: 5.1116e-04
Epoch 7/20
35004/35004 [==============================] - 148s 4ms/step - loss: 4.4975e-04
Epoch 8/20
35004/35004 [==============================] - 151s 4ms/step - loss: 4.1095e-04
Epoch 9/20
35004/35004 [==============================] - 146s 4ms/step - loss: 3.7360e-04
Epoch 10/20
35004/35004 [==============================] - 149s 4ms/step - loss: 3.3797e-04
Epoch 11/20
35004/35004 [==============================] - 150s 4ms/step - loss: 3.1775e-04
Epoch

In [82]:
x_test  = data_test.values

x_test = sc.transform(x_test)
x_test
X_test = []
for i in range(time_step, len(x_test)):
    X_test.append(x_test[i-time_step: i, 0])
X_test= np.array(X_test)
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
X_test.shape
prediccion = model.predict(X_test)



In [86]:
x_test[1:5, 0:5]


array([[1.33333333, 0.        , 0.16666667, 0.        , 0.04347826],
       [1.33333333, 0.        , 0.16666667, 0.        , 0.08695652],
       [1.33333333, 0.        , 0.16666667, 0.        , 0.13043478],
       [1.33333333, 0.        , 0.16666667, 0.        , 0.17391304]])

In [78]:
prediccion = sc.inverse_transform(prediccion)

ValueError: non-broadcastable output operand with shape (8700,1) doesn't match the broadcast shape (8700,6)

In [ ]:
#Grafica de valores
# Y_test #Aun no defnido 
plt.plot(prediccion, color='blue', label='Predicción de consumo')
plt.xlabel('Tiempo')
plt.ylabel('Consumo')
plt.legend()
plt.show()
